settings:
  # Команда, которая автоматически выполнится от консоли при одобрении видео.
  # Ты можешь вписать сюда абсолютно любую команду своей сборки (выдать кейс, монеты или префикс)
  reward-command: "cases give %player% super 1"